CREATE DATABASE IF NOT EXISTS customer;

USE my_database;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS customer (
  id INT AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  age INT NOT NULL,
);

INSERT INTO users (password)
VALUES ('${DB_PASSWORD}');
